### ISSUE TITLE
Xterm上で任意のプロセスを終了させるためにCtrl+Dを押すとペインが終了してしまう

### ISSUE THREAD

**Issue by corrupt952** [konoyono/okadash#1]
## 概要
Xterm上で任意のプロセスを終了させるためにCtrl+Dを押すとペインが終了してしまう.
シェル上ではCtrlプレフィックスの操作は多々あるため、できれば別のショートカットキーにペインの終了を割り当ててほしい.

## 再現方法
1. `irb`などのインタプリタを起動する
2. Ctrl+Dを押すとペインが終了する

**Comment by konoyono** [comment]
Xtermサポート終了したのでCloseします 🙇
