### ISSUE TITLE
DeveloperToolsを組み込んでほしい

### ISSUE THREAD

**Issue by kazto** [konoyono/okadash#19]
同じElectronアプリのHyperターミナル（ https://hyper.is ）では、メニューからDeveloper Toolsを起動できるようになっています。
okadashにもこれを組み込むと、皆さんデバッグとか見た目の調整とかやりやすくなると思います。

**Comment by konoyono** [comment]
起票いただき、ありがとうございます！とても嬉しいです！！

メニューの `View -> Toggle Developer Tools` から起動できると思うのですが、
ご確認いただけますでしょうか？

上記の挙動とは別のものを期待されているということであれば、ご指摘ください！！

**Comment by kazto** [comment]
ありました。。。大変失礼いたしました！
