### ISSUE TITLE
Okadash almost can't do anything if all board deleted

### ISSUE THREAD

**Issue by fruitriin** [konoyono/okadash#35]
I found something dead lock in okadash.

At first, you delete all boards. (Just my fail)
Second, you lost all the board definition as json.

I can't add any Item, and I can't import from valid .json because I don't have it.
( If you export blank bord, just `""` file is export. )

And save invalid board setting if you shutdown okadash, so it wakeup with invalid bord.

I think its bug. How about do you think?

**Comment by fruitriin** [comment]
okadash may feat that stop delete a last board. ( just idea.)

**Comment by konoyono** [comment]
Thanks for reporting!

Making impossible to delete the last board sounds a good idea.

Or, if there isn't any board definitions, automatically create a new one from the default board sounds good.

**Comment by konoyono** [comment]
Solved #42
