### ISSUE TITLE
Open new small pane from input URL

### ISSUE THREAD

**Issue by konoyono** [konoyono/okadash#38]
URL と項目名を入力して、スモールペインを開けるようにしたい。
いちいち preferences から設定するのが面倒なので。

**Comment by fruitriin** [comment]
スモールペイン限定ですか？ミドルペインでMeetsを開いているのでミドルペインでもURL開けたらうれしいなあ

**Comment by konoyono** [comment]
全ペイン対応できそうならしてしまいたいですなぁ

**Comment by konoyono** [comment]
#47 にて対応
