### ISSUE TITLE
Can't Window share in Okadash[Enhancement]

### ISSUE THREAD

**Issue by fruitriin** [konoyono/okadash#43]
Okadash open hangout(meets), I can join its. I can talk.
I can also view another's window sharing.
but if you enable share window, it says something error happens.

<img width="402" alt="スクリーンショット 2020-04-28 10 52 25" src="https://user-images.githubusercontent.com/18308639/80438254-b40dc380-893e-11ea-852b-8189be93f6c7.png">

I think something permission or so on.

I hope this problem is solved. ( but not have to )

**Comment by konoyono** [comment]
検証してみましたが、おそらく `webview` のセキュリティ上の制約な気がします 😢 

![image](https://user-images.githubusercontent.com/8579173/80552204-d49e5200-8a00-11ea-94ad-ee07ad6d8ae5.png)
