### ISSUE TITLE
 The Scrapbox cannot be displayed properly.

### ISSUE THREAD

**Issue by konoyono** [konoyono/okadash#7]
Some problems happened.
It may be a compatibility issue with webview tag in Electron.

https://scrapbox.io/

**Comment by valerauko** [comment]
> Some problems happened

Any details what exactly happened?

**Comment by konoyono** [comment]
thx for your comment.
I'll explain what's happened in detail tomorrow.
Good night ⭐️

**Comment by valerauko** [comment]
It seems to load without any issues...
![Screenshot from 2019-11-06 13-50-27](https://user-images.githubusercontent.com/6322484/68269252-6bb2ce80-009c-11ea-9fa3-259eb86ae917.png)

**Comment by konoyono** [comment]
It worked without any problems, as you told.
Close this issue. Thx!!
